### ISSUE TITLE
Error: signInWithEmailAndPassword failed: Second argument "password" must be a valid string.

### ISSUE THREAD

**Issue by lucasavila00** [colinjlacy/firebase-ionic-2-demo#1]
When logging in, the console throw this error.
The fix:
On file /app/pages/components/login.components.ts, on line 28 switch from

```
<ion-input [(ngModel)]="password" type="password"></ion-input>
```

to 

```

<ion-input [(ngModel)]="userPassword" type="password"></ion-input>
```

**Comment by colinjlacy** [comment]
Thanks for catching and submitting the PR.  Closing

**Comment by colinjlacy** [comment]
was fixed in this branch: https://github.com/colinjlacy/firebase-ionic-2-demo/pull/2
