### ISSUE TITLE
Ionic serve not working

### ISSUE THREAD

**Issue by sijintv** [colinjlacy/firebase-ionic-2-demo#3]
TypeScript error: app/app.ts(4,27): Error TS2307: Cannot find module 'firebase'

**Comment by sijintv** [comment]
btw, 
`typings install dt~firebase --global --save`
fixed it.
Thanks

**Comment by aaronksaunders** [comment]
this installs the incorrect version of the typings...

**Comment by rojagit** [comment]
what is dt~firebase ? and how does one even come across modules like this ?

**Comment by aaronksaunders** [comment]
I am not sure that the answer above is still correct, let me take a look later today and respond; but basically that is the typescript definition file for firebase

**Comment by colinjlacy** [comment]
I had a moment to take a look into the node package for firebase and the typings are included in there.  Is there a direct way to include those typings that you know of?

**Comment by colinjlacy** [comment]
Ok, figure this one out.  And the amount of coffee involved was pretty expensive.  

Make sure you've installed Firebase 3 via NPM.  Then in the command line, run the following:

```
typings install npm~firebase --save
```

That should install it into the `dependencies` property in `typings.json`.  

Next, you'll notice there's a new file added called `typings/index.ts`, with a reference to the Firebase 3 typings.  That's not what you want.  Instead you'll add your new reference to `typings/main.ts`.  Looks like this:

```
/// <reference path="main/ambient/es6-shim/index.d.ts" />
/// <reference path="modules/firebase/index.d.ts" />
```

Awesome.  Now you should be able to start your application, and in compiling your TS you shouldn't have any errs.

**Comment by jose2007kj** [comment]
@colinjlacy...thankyou...thanks a lot.....
